server:
  port: 8888
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bike?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#mongodb
  data:
    mongodb:
      port: 27017
      host: 192.168.1.201
      username: bike
      password: bike
      database: bike
#视图解析
  mvc:
    view:
      prefix: /pages/
      suffix: .html
#redis
  redis:
    host: 192.168.1.201
    port: 6379
    password: root
    jedis:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
# MyBatis注解形式扫描实体类路径
# MyBatis XML形式配置文件路径
mybatis:
  type-aliases-package: my.suveng.veng_bike_server.pojo.mysql
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:target/classes/my/suveng/veng_bike_server/dao/*.xml
