server:
  port: 8888
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bike?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
