server:
  port: 8888
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bike?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#mongodb
  data:
    mongodb:
      port: 27017
      host: 132.232.71.94
      database: bike
#视图解析
  mvc:
    view:
      prefix: /pages/
      suffix: .html
#redis
  redis:
    host: 132.232.71.94
    port: 6379
#    password: root
    jedis:
      pool:
        max-wait: 1
        max-active: 8
        max-idle: 8
        min-idle: 0
  devtools:
    restart:
      additional-paths: src/main/java
# MyBatis注解形式扫描实体类路径
# MyBatis XML形式配置文件路径
mybatis:
  type-aliases-package: my.suveng.veng_bike_server.*.pojo.mysql
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:my/suveng/veng_bike_server/*/dao/*.xml
