server:
  port: 8888
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bike?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#mongodb
  data:
    mongodb:
      port: 27017
      host: 192.168.1.101
      username: bike
      password: bike
      database: bike
#视图解析
  mvc:
    view:
      prefix: /pages/
      suffix: .html